---
#This code use to download the Templete directly from website, then unzip it. Along with service installed
- hosts: webservers
  remote_user: ubuntu
  become: yes
  gather_facts: no
  tasks:
    - name: install apache2
      apt: name=apache2 state=latest update_cache=true
    - name: install php
      apt: name=php state=latest
    - name: install zip
      apt: name=zip state=latest
    - name: restart 
      service: name=apache2 state=restarted
    - name: Download Themes
      get_url:
        url: https://downloads.wordpress.org/theme/airi.zip
        dest: /tmp
    - name: unzip
      unarchive:
        src: /tmp/airi.1.0.10.zip
        dest: /tmp
        remote_src: yes
    - name: Synchronization of two paths both on the control machine
      copy:
        src: /tmp/airi/
        dest: /var/www/html        
        remote_src: yes
    - name: restart apache2
      service: name=apache2 state=restarted

