---
- name: "facts"  
  hosts: local
  connection: local
  become: true
  gather_facts: true
  vars_files:
    - aws_keys.yml
  tasks:
    - name: "setup list"
      ec2_instance_facts:
        filters:
          availability-zone: us-east-2
      register: ec2_instance_facts
    -  set_fact:
         msg: "{{ ec2_instance_facts }} "
    - debug: var=msg

